#!/bin/bash 
#print hello world  
echo "hello  world"
echo hello world
#print hello " world (\ not print ) 
echo "hello \" world"
#print list of files : file1 
#                      file2 
#                      file3 
#                      file4 in users.txt
echo "list of files :" * >> users.txt:Wq

